### ISSUE TITLE
打开页面报错

### ISSUE THREAD

**Issue by alanlah** [harrietjia/vue-pdf-show#1]
**TypeError: PDFJS.getDocument(...).then is not a function**

Uncaught SyntaxError: Unexpected token '<'
pdf.js:3089 Uncaught (in promise) Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

**Comment by harrietjia** [comment]
https://blog.csdn.net/qq_38188485/article/details/104452542 博客已增加解决方法
